 
 name: NormCI
 
 on: push
 
 jobs:
   norm:
     runs-on: macos-11.0
 
     steps:

       - name: checkout git repository
         uses: actions/checkout@v2

       - name: ls
         run: ls

       - name: change directory
         run: cd test_tests && make test
